version: "3"

services:
  db:
    # latest image as of writing
    image: postgres:12.17
    environment:
      POSTGRES_USER: "user"
      POSTGRES_DATABASE: cards
      POSTGRES_PASSWORD: "heresapassword"
    volumes:
      - "dbvolume:/var/lib/postgresql/data"
  flask:
    build: .
    ports:
      - "8080:8080"

volumes:
  dbvolume:
