version: "3"

services:
  db:
    # latest image as of writing
    image: postgres:12.17
    environment:
      POSTGRES_USER: "user"
      POSTGRES_DATABASE: cards
      POSTGRES_PASSWORD: "heresapassword"
    volumes:
      - "dbvolume:/var/lib/postgresql/data"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: your@email.com
      PGADMIN_DEFAULT_PASSWORD: yourpassword
    ports:
      - "8081:80"

  flask:
    build: .
    ports:
      - "8080:8080"

volumes:
  dbvolume:
