version: "3"

services:
  db:
    image: postgres:16.2
    environment:
      POSTGRES_USER: cards
      POSTGRES_DATABASE: cards
      POSTGRES_PASSWORD: heresapassword
    volumes:
      - "dbvolume:/var/lib/postgresql/data"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: cards@email.com
      PGADMIN_DEFAULT_PASSWORD: heresapassword
    ports:
      - "8081:80"

  flask:
    build: .
    ports:
      - "8080:8080"

volumes:
  dbvolume:
