version: "3"

services:
  db:
    # latest image as of writing
    image: postgres:16.2
    environment:
      POSTGRES_DATABASE: card-tracker
      POSTGRES_PASSWORD: "heresapassword"
    volumes:
      - "dbfiles:/var/lib/postgresql/data"
  flask:
    build: .
    ports:
      - "8080:8080"

volumes:
  dbfiles:
  kafkafiles:
